# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_gui(object):
    def setupUi(self, gui):
        gui.setObjectName("gui")
        gui.resize(500, 300)
        font = QtGui.QFont()
        font.setPointSize(13)
        gui.setFont(font)
        self.gridLayoutWidget = QtWidgets.QWidget(gui)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 481, 281))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.scale_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.scale_spinBox.setMinimum(1)
        self.scale_spinBox.setMaximum(100)
        self.scale_spinBox.setProperty("value", 50)
        self.scale_spinBox.setObjectName("scale_spinBox")
        self.gridLayout.addWidget(self.scale_spinBox, 4, 1, 1, 2)
        self.duration_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.duration_spinBox.setMaximum(10000)
        self.duration_spinBox.setProperty("value", 250)
        self.duration_spinBox.setObjectName("duration_spinBox")
        self.gridLayout.addWidget(self.duration_spinBox, 3, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.outputPath_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.outputPath_lineEdit.setObjectName("outputPath_lineEdit")
        self.gridLayout.addWidget(self.outputPath_lineEdit, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.browse_outputPath_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.browse_outputPath_btn.setObjectName("browse_outputPath_btn")
        self.gridLayout.addWidget(self.browse_outputPath_btn, 2, 2, 1, 1)
        self.inputPath_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.inputPath_lineEdit.setObjectName("inputPath_lineEdit")
        self.gridLayout.addWidget(self.inputPath_lineEdit, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.type_ComboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.type_ComboBox.setEditable(False)
        self.type_ComboBox.setObjectName("type_ComboBox")
        self.gridLayout.addWidget(self.type_ComboBox, 0, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.browse_inputPath_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.browse_inputPath_btn.setObjectName("browse_inputPath_btn")
        self.gridLayout.addWidget(self.browse_inputPath_btn, 1, 2, 1, 1)
        self.export_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.export_btn.setObjectName("export_btn")
        self.gridLayout.addWidget(self.export_btn, 7, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 6, 1, 1, 1)
        self.status_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        font.setKerning(True)
        self.status_label.setFont(font)
        self.status_label.setStyleSheet("color: rgb(150, 150, 150);")
        self.status_label.setObjectName("status_label")
        self.gridLayout.addWidget(self.status_label, 7, 0, 1, 2)

        self.retranslateUi(gui)
        QtCore.QMetaObject.connectSlotsByName(gui)

    def retranslateUi(self, gui):
        _translate = QtCore.QCoreApplication.translate
        gui.setWindowTitle(_translate("gui", "Image to GIF"))
        self.label_2.setText(_translate("gui", "Output Path"))
        self.label.setText(_translate("gui", "Images Path"))
        self.label_5.setText(_translate("gui", "Input Type"))
        self.browse_outputPath_btn.setText(_translate("gui", "..."))
        self.label_4.setText(_translate("gui", "Scale (%)"))
        self.label_3.setText(_translate("gui", "Duration (ms)"))
        self.browse_inputPath_btn.setText(_translate("gui", "..."))
        self.export_btn.setText(_translate("gui", "Export"))
        self.status_label.setText(_translate("gui", "Application Loaded."))
